// we will pretend this file is generated by a hardware generator
module mod (
    input  logic clk,
    input  logic rst,
    input  logic[3:0] in,
    output logic[3:0] out
);

always_ff @(posedge clk, posedge rst) begin
    if (rst)
        out <= 0;
    else
        out <= in;
end

endmodule

module top;

logic clk, rst;
logic[3:0] in, out;

mod dut(.*);

initial begin
    clk = 0;
    in = 0;
end

// clock logic
always clk = #5 ~clk;

initial begin
    $dumpfile("waveform3.vcd");
    $dumpvars(0, top);

    rst = 0;
    #1;
    rst = 1;
    #1;
    rst = 0;
    for (int i = 1; i <= 10; i++) begin
        @(negedge clk);
        in = i;
        @(posedge clk);
    end
    
    $finish;
end

endmodule
