#!/usr/bin/env python

import os
import pkgutil
import subprocess
import sys

# find the lib
libpath = pkgutil.get_loader("libhgdb").path
exit(subprocess.call(["vsim"] + sys.argv[1:] + ["-pli", libpath]))
