name: Build Docker test image

on:
  push:
    branches:
      - master
    paths:
      - docker/test/Dockerfile
      - docker/lint/Dockerfile

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker test image 📦
      shell: bash
      run: |
        cd docker
        cd test && docker build . -t keyiz/hgdb:test && cd ../
        cd lint && docker build . -t keyiz/hgdb:lint && cd ../
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push keyiz/hgdb:test
        docker push keyiz/hgdb:lint
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
